trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and push stage
  variables:
  - group: 'rm-function-apps-dev-env-variable-group'
  jobs:
  - template: azure-pipelines-build-template.yml
    parameters:
      dockerfilePath: '**/Dockerfile'
      tag: '$(Build.BuildId)'