parameters:
  - name: vmImageName
    type: string
    default: 

jobs:
  - deployment:
    displayName: $(environment)-Deploy
    pool:
      vmImage: $(vmImageName)
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
             buildType: 'specific'
             project: 'Maven-kubernetes-yaml-pipeline'
             definition: '$(pipeline-name)'
             specificBuildWithTriggering: true
             buildVersionToDownload: 'latest'
             artifactName: 'drop'
             targetPath: '$(Pipeline.Workspace)'

          - task: qetza.replacetokens.replacetokens-task.replacetokens@5
            displayName: 'Replace tokens in **/*.yaml'
            inputs:
              rootDirectory: '$(Pipeline.Workspace)'
              targetFiles: '**/springboot-dep-svc-new.yaml'
      
      
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: 'default'
              manifests: '$(Pipeline.Workspace)/springboot-dep-svc-new.yaml'
