trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and push stage
  variables:
  - group: 'rm-function-apps-dev-env-variable-group'
  jobs:
  - template: azure-pipelines-build-template.yml
    parameters:
      dockerfilePath: '**/Dockerfile'
      tag: '$(Build.BuildId)'
  
- stage: Deploytodev
  displayName: Deploytodev
  condition: succeeded()
  dependsOn: Build
  variables:
  - group: 'rm-function-apps-dev-env-variable-group'
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      environment: 'DEV-template'