  parameters:
  - name: vmImageName
    type: string
    default:
  jobs:
  - deployment:
    displayName: $(environment)-Deploy
    pool:
      vmImage: $(vmImageName)
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
             buildType: 'specific'
             project: 'ce38e970-3a2b-471b-a7c7-6001d298e3ae'
             definition: '10'
             specificBuildWithTriggering: true
             buildVersionToDownload: 'latest'
             artifactName: 'drop'
             targetPath: '$(Pipeline.Workspace)'

          - task: qetza.replacetokens.replacetokens-task.replacetokens@5
            displayName: 'Replace tokens in **/*.yaml'
            inputs:
              rootDirectory: '$(Pipeline.Workspace)'
              targetFiles: '**/springboot-dep-svc-new.yaml'
      
      
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: 'default'
              manifests: '$(Pipeline.Workspace)/springboot-dep-svc-new.yaml'
