trigger:
- master

resources:
- repo: self
variables:
  # Container registry service connection established during pipeline creation
  - group: 'rm-function-apps-dev-env-variable-group'
  - name: tag
    value: '$(Build.BuildId)'
  - name: dockerfilePath
    value: '**/Dockerfile'
  - name: dockerRegistryServiceConnection
    value: acr-sc
  

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - template: azure-pipelines-build-template.yml