# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'acr-sc'
  imageRepository: 'mavenpipeline'
  containerRegistry: 'acrnew09.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'mypipesecret'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Buildstage
  displayName: Build and push stage
  jobs:
  - job: Buildjob
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'drop'
        publishLocation: 'pipeline'
    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploytodev
  displayName: Deploytodev
  dependsOn: Build
  jobs:
  - job: deploytodev
    displayName: deploytodev
    environment: dev
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
    - task: qetza.replacetokens.replacetokens-task.replacetokens@5
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: '$(system.defaultworkingdirectory)'
        targetFiles: '**/springboot-dep-svc-new.yaml'
      
       
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kube-sc'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(system.defaultworkingdirectory)/springboot-dep-svc-new.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        azureSubscriptionEndpointForSecrets: 'az-rm-sc'
        azureContainerRegistry: 'acrnew09.azurecr.io'
        secretName: 'mypipesecret'
        
- stage: Deploytotest
  displayName: Deploytotest
  dependsOn: Deploytodev
  jobs:
  - job: 
    pool:
      vmImage: $(vmImageName)
      environment: 'test'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
    - task: qetza.replacetokens.replacetokens-task.replacetokens@5
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: '$(system.defaultworkingdirectory)'
        targetFiles: '**/springboot-dep-svc-new.yaml'
      
       
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kube-sc'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(system.defaultworkingdirectory)/springboot-dep-svc-new.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        azureSubscriptionEndpointForSecrets: 'az-rm-sc'
        azureContainerRegistry: 'acrnew09.azurecr.io'
        secretName: 'mypipesecret'

- stage: Deploytoprod
  displayName: Deploytoprod
  dependsOn: Deploytotest
  jobs:
  - job: 
    pool:
      vmImage: $(vmImageName)
      environment: 'prod'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
    - task: qetza.replacetokens.replacetokens-task.replacetokens@5
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: '$(system.defaultworkingdirectory)'
        targetFiles: '**/springboot-dep-svc-new.yaml'
      
      
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'kube-sc'
        namespace: 'default'
        manifests: '$(system.defaultworkingdirectory)/springboot-dep-svc-new.yaml'
      


    
    
  
          
            
            
         
          
