apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: mydockercontainerregistrydec20.azurecr.io/kube-image:#{Build.BuildId}#
        ports:
        - containerPort: 8080
		
		
---

kind: Service
apiVersion: v1
metadata:
  name: maven-service
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
