apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deploy
  labels:
    app: maven-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-deploy
  template:
    metadata:
      labels:
        app: maven-deploy
    spec:
      containers:
      - name: acrserver
        image: azacrjan23.azurecr.io/springboot-maven-course-micro-svc:4 
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: jenkins-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 33333
      targetPort: 33333
  type: LoadBalancer
